/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Toolkit;

import javax.swing.ImageIcon;

/**
 *
 * @author Саша
 */
public class Main_Internal_Frame extends javax.swing.JInternalFrame {

    /**
     * Creates new form MainInternalFpame
     */
    public Main_Internal_Frame() {
    	this.setFrameIcon(new ImageIcon(Toolkit.getDefaultToolkit().getImage("images/icons/icon16.png")));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jToolBar = new javax.swing.JToolBar();
        jButton1_jToolBar = new javax.swing.JButton();
        jButton2_jToolBar = new javax.swing.JButton();
        jButton3_jToolBar = new javax.swing.JButton();
        jTabbedPane = new javax.swing.JTabbedPane();
        status_jPanel = new javax.swing.JPanel();
        //jLabel_status_jPanel = new javax.swing.JLabel();

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0};
        layout.rowHeights = new int[] {0, 5, 0};
        getContentPane().setLayout(layout);
        
        jToolBar.setFloatable(false);
        jToolBar.setRollover(true);

        jButton1_jToolBar.setText("jButton1");
        jButton1_jToolBar.setFocusable(false);
        jButton1_jToolBar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1_jToolBar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar.add(jButton1_jToolBar);

        jButton2_jToolBar.setText("jButton2");
        jButton2_jToolBar.setFocusable(false);
        jButton2_jToolBar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2_jToolBar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar.add(jButton2_jToolBar);

        jButton3_jToolBar.setText("jButton3");
        jButton3_jToolBar.setFocusable(false);
        jButton3_jToolBar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3_jToolBar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar.add(jButton3_jToolBar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 6);
        getContentPane().add(jToolBar, gridBagConstraints);

        jTabbedPane.setMinimumSize(new java.awt.Dimension(5, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        getContentPane().add(jTabbedPane, gridBagConstraints);

        status_jPanel.setMaximumSize(new java.awt.Dimension(32767, 22));
        status_jPanel.setMinimumSize(new java.awt.Dimension(100, 22));
        status_jPanel.setPreferredSize(new java.awt.Dimension(495, 22));

        //jLabel_status_jPanel.setText("jLabel1");

        /*
        javax.swing.GroupLayout status_jPanelLayout = new javax.swing.GroupLayout(status_jPanel);
        status_jPanel.setLayout(status_jPanelLayout);
        status_jPanelLayout.setHorizontalGroup(
            status_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_status_jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
        );
        status_jPanelLayout.setVerticalGroup(
            status_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_status_jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );
        */

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 5, 5);
        getContentPane().add(status_jPanel, gridBagConstraints);

        pack();
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    public javax.swing.JButton jButton1_jToolBar;
    public javax.swing.JButton jButton2_jToolBar;
    public javax.swing.JButton jButton3_jToolBar;
    //public javax.swing.JLabel jLabel_status_jPanel;
    public javax.swing.JTabbedPane jTabbedPane;
    public javax.swing.JToolBar jToolBar;
    public javax.swing.JPanel status_jPanel;
    // End of variables declaration                   
}
