package gui.settings;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;

import javax.swing.JPanel;

import controller.Controller;
import gui.library.My_JFileChooser;
import lang.Lang;
import settings.Settings;

public class BackUP_Setting_Panel extends JPanel{


		private static final long serialVersionUID = -3627676349323710842L;
		/**
	     * Creates new form BackUpPanel
	     */
	    public BackUP_Setting_Panel() {
	   
	    	initComponents();
	    	jLabel_Title.setText(Lang.getInstance().translate("BackUP Panel"));
	    	 jCheckBox_Enable_BackUp.setText(Lang.getInstance().translate("Enable BackUP"));
	    	 jCheckBox_Ask_To_Start.setText(Lang.getInstance().translate("Ask from start"));
	    	 jLabel_Paht_DIR.setText(Lang.getInstance().translate("BackUP DIR"));
	    	 jButton_Paht_DIR.setText(Lang.getInstance().translate("Browse")+"...");
	    	 
	    	 jCheckBox_Enable_BackUp.setSelected(Settings.getInstance().getbacUpEnabled());
	    	 jCheckBox_Ask_To_Start.setSelected(Settings.getInstance().getbacUpAskToStart());
	    	 jTextField_BuckUp_Dip.setText(Settings.getInstance().getBackUpDir());
	    	
	    	 jButton_Paht_DIR.addActionListener(new ActionListener() {
	             public void actionPerformed(ActionEvent e) {
	                 My_JFileChooser fileopen = new My_JFileChooser();  
	                 fileopen.setFileSelectionMode(My_JFileChooser.DIRECTORIES_ONLY);
	                 fileopen.setCurrentDirectory(new File(jTextField_BuckUp_Dip.getText()));
	                 int ret = fileopen.showDialog(null, Lang.getInstance().translate("Set BackUp dir"));                
	                 if (ret == My_JFileChooser.APPROVE_OPTION) {
	                	 jTextField_BuckUp_Dip.setText(fileopen.getSelectedFile().toString());
	                 }
	             }
	         });
	    	 
	    	 
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {
	        java.awt.GridBagConstraints gridBagConstraints;

	        jLabel_Title = new javax.swing.JLabel();
	        jCheckBox_Enable_BackUp = new javax.swing.JCheckBox();
	        jLabel_Paht_DIR = new javax.swing.JLabel();
	        jTextField_BuckUp_Dip = new javax.swing.JTextField();
	        jButton_Paht_DIR = new javax.swing.JButton();
	        jCheckBox_Ask_To_Start = new javax.swing.JCheckBox();
	        jLabel3 = new javax.swing.JLabel();

	        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
	        layout.columnWidths = new int[] {0, 5, 0, 5, 0};
	        layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
	        setLayout(layout);

	        jLabel_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
	        jLabel_Title.setText("jLabel1");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridx = 0;
	        gridBagConstraints.gridy = 0;
	        gridBagConstraints.gridwidth = 5;
	        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
	        gridBagConstraints.weightx = 0.2;
	        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
	        add(jLabel_Title, gridBagConstraints);

	        jCheckBox_Enable_BackUp.setText("jCheckBox1");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridx = 0;
	        gridBagConstraints.gridy = 2;
	        gridBagConstraints.gridwidth = 3;
	        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
	        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
	        add(jCheckBox_Enable_BackUp, gridBagConstraints);

	        jLabel_Paht_DIR.setText("jLabel2");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridx = 0;
	        gridBagConstraints.gridy = 4;
	        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
	        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
	        add(jLabel_Paht_DIR, gridBagConstraints);

	        jTextField_BuckUp_Dip.setText("jTextField1");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridx = 2;
	        gridBagConstraints.gridy = 4;
	        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
	        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
	        gridBagConstraints.weightx = 0.2;
	        add(jTextField_BuckUp_Dip, gridBagConstraints);

	        jButton_Paht_DIR.setText("jButton1");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridx = 4;
	        gridBagConstraints.gridy = 4;
	        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
	        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
	        add(jButton_Paht_DIR, gridBagConstraints);

	        jCheckBox_Ask_To_Start.setText("jCheckBox2");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridx = 0;
	        gridBagConstraints.gridy = 6;
	        gridBagConstraints.gridwidth = 3;
	        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
	        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
	        add(jCheckBox_Ask_To_Start, gridBagConstraints);

	        jLabel3.setText("jLabel3");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridx = 0;
	        gridBagConstraints.gridy = 8;
	        gridBagConstraints.gridwidth = 5;
	        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	        gridBagConstraints.weightx = 0.1;
	        gridBagConstraints.weighty = 0.1;
	        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
	        add(jLabel3, gridBagConstraints);
	    }// </editor-fold>                        


	    // Variables declaration - do not modify                     
	    private javax.swing.JButton jButton_Paht_DIR;
	   public javax.swing.JCheckBox jCheckBox_Ask_To_Start;
	    public javax.swing.JCheckBox jCheckBox_Enable_BackUp;
	    private javax.swing.JLabel jLabel3;
	    private javax.swing.JLabel jLabel_Paht_DIR;
	    private javax.swing.JLabel jLabel_Title;
	    public javax.swing.JTextField jTextField_BuckUp_Dip;
	    // End of variables declaration                   
	}
