package gui.items.accounts;

import javax.swing.JPanel;

public class Info_Account_Transactions_Panel extends JPanel {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	
	
	public Info_Account_Transactions_Panel(){
		
		 
		        initComponents();
		    }

		    /**
		     * This method is called from within the constructor to initialize the form.
		     * WARNING: Do NOT modify this code. The content of this method is always
		     * regenerated by the Form Editor.
		     */
		    @SuppressWarnings("unchecked")
		    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
		    private void initComponents() {
		        java.awt.GridBagConstraints gridBagConstraints;

		        jLabel1 = new javax.swing.JLabel();
		        jScrollPane1 = new javax.swing.JScrollPane();
		        jTable1 = new javax.swing.JTable();
		        jLabel2 = new javax.swing.JLabel();

		        setLayout(new java.awt.GridBagLayout());

		        jLabel1.setText("jLabel1");
		        gridBagConstraints = new java.awt.GridBagConstraints();
		        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
		        gridBagConstraints.weightx = 0.1;
		        gridBagConstraints.insets = new java.awt.Insets(8, 8, 4, 8);
		        add(jLabel1, gridBagConstraints);

		        tab_Model = new Model_Account_Transactions();
		        
		        jTable1.setModel(tab_Model);
		        jScrollPane1.setViewportView(jTable1);

		        gridBagConstraints = new java.awt.GridBagConstraints();
		        gridBagConstraints.gridx = 0;
		        gridBagConstraints.gridy = 1;
		        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
		        gridBagConstraints.weightx = 0.1;
		        gridBagConstraints.weighty = 0.1;
		        gridBagConstraints.insets = new java.awt.Insets(0, 8, 4, 8);
		        add(jScrollPane1, gridBagConstraints);

		        jLabel2.setText("jLabel2");
		        gridBagConstraints = new java.awt.GridBagConstraints();
		        gridBagConstraints.gridx = 0;
		        gridBagConstraints.gridy = 2;
		        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
		        gridBagConstraints.weightx = 0.1;
		        gridBagConstraints.insets = new java.awt.Insets(0, 8, 8, 8);
		        add(jLabel2, gridBagConstraints);
		    }// </editor-fold>                        


		    // Variables declaration - do not modify                     
		    private javax.swing.JLabel jLabel1;
		    private javax.swing.JLabel jLabel2;
		    private javax.swing.JScrollPane jScrollPane1;
		    private javax.swing.JTable jTable1;
		   public Model_Account_Transactions tab_Model;
		    // End of variables declaration                   
		}

