package org.erachain.gui2;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.Enumeration;

import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTree;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreePath;

import org.erachain.core.BlockChain;
import org.erachain.gui.Wallets.WalletsManagerSplitPanel;
import org.erachain.gui.bank.IssueSendPaymentOrder;
import org.erachain.gui.bank.MyOrderPaimentsSplitPanel;
import org.erachain.gui.items.accounts.AccountsNameSearchSplitPanel;
import org.erachain.gui.items.accounts.MyAccountsSplitPanel;
import org.erachain.gui.items.accounts.MyLoansSplitPanel;
import org.erachain.gui.items.assets.*;
import org.erachain.gui.items.imprints.ImprintsFavoriteSplitPanel;
import org.erachain.gui.items.imprints.ImprintsSearchSplitPanel;
import org.erachain.gui.items.imprints.IssueImprintPanel;
import org.erachain.gui.items.imprints.MyImprintsTab;
import org.erachain.gui.items.link_hashes.IssueLinkedHashPanel;
import org.erachain.gui.items.link_hashes.SearchLinkedHash;
import org.erachain.gui.items.mails.IncomingMailsSplitPanel;
import org.erachain.gui.items.mails.MailSendPanel;
import org.erachain.gui.items.mails.OutcomingMailsSplitPanel;
import org.erachain.gui.items.other.OtherConsolePanel;
import org.erachain.gui.items.other.OtherSearchBlocks;
import org.erachain.gui.items.other.OtherSplitPanel;
import org.erachain.gui.items.persons.*;
import org.erachain.gui.items.polls.IssuePollPanel;
import org.erachain.gui.items.polls.PollsFavoriteSplitPanel;
import org.erachain.gui.items.polls.Polls_My_SplitPanel;
import org.erachain.gui.items.polls.SearchPollsSplitPanel;
import org.erachain.gui.items.records.FavoriteTransactionsSplitPanel;
import org.erachain.gui.items.records.MyTransactionsSplitPanel;
import org.erachain.gui.items.records.SearchTransactionsSplitPanel;
import org.erachain.gui.items.records.UnconfirmedTransactionsPanel;
import org.erachain.gui.items.statement.FavoriteStatementsSplitPanel;
import org.erachain.gui.items.statement.IssueDocumentPanel;
import org.erachain.gui.items.statement.SearchStatementsSplitPanel;
import org.erachain.gui.items.statement.StatementsMySplitPanel;
import org.erachain.gui.items.statuses.IssueStatusPanel;
import org.erachain.gui.items.statuses.SearchStatusesSplitPanel;
import org.erachain.gui.items.statuses.StatusesFavoriteSplitPanel;
import org.erachain.gui.items.templates.IssueTemplatePanel;
import org.erachain.gui.items.templates.SearchTemplatesSplitPanel;
import org.erachain.gui.items.templates.TemplatesFavoriteSplitPanel;
import org.erachain.gui.items.unions.IssueUnionPanel;
import org.erachain.gui.items.unions.MyUnionsTab;
import org.erachain.gui.items.unions.SearchUnionSplitPanel;
import org.erachain.gui.library.MSplitPane;
import org.erachain.gui.telegrams.ALLTelegramPanel;
import org.erachain.gui.telegrams.TelegramSplitPanel;
import org.erachain.lang.Lang;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * @author ����
 */
public class MainPanel extends javax.swing.JPanel {

    /**
     *
     */
    private static final long serialVersionUID = 1L;
    private static MainPanel instance;
    public MainLeftPanel mlp;
    public MSplitPane jSplitPane1;
    public MTabbedPanel jTabbedPane1;

    private MainPanel() {
        initComponents();
 //       jSplitPane1.M_setDividerSize(40);
    }

    // Variables declaration - do not modify

    /**
     * Creates new form split_1
     */

    public static MainPanel getInstance() {
        if (instance == null) {
            instance = new MainPanel();
        }

        return instance;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSplitPane1 = new MSplitPane();
        jSplitPane1.set_CloseOnOneTouch(jSplitPane1.ONE_TOUCH_CLOSE_LEFT_TOP); // set
        // one
        // touch
        // close
        // LEFT
        jTabbedPane1 = new MTabbedPanel(JTabbedPane.TOP, JTabbedPane.SCROLL_TAB_LAYOUT);
        mlp = new MainLeftPanel();
        jTabbedPane1.addMouseListener(new MouseListener() {

            @Override
            public void mouseClicked(MouseEvent arg0) {
                // TODO Auto-generated method stub

            }

            @Override
            public void mouseEntered(MouseEvent arg0) {
                // TODO Auto-generated method stub

            }

            @Override
            public void mouseExited(MouseEvent arg0) {
                // TODO Auto-generated method stub

            }

            @Override
            public void mousePressed(MouseEvent arg0) {
                // TODO Auto-generated method stub
                Component cc = arg0.getComponent();
                if (cc.getClass().getSimpleName().equals("MTabbedPanel")) {
                    MTabbedPanel mt = (MTabbedPanel) cc;

                    // find path from name node
                    int index = mt.getSelectedIndex();
                    if (index >= 0) {
                        DefaultMutableTreeNode ss = getNodeByName(jTabbedPane1.getTitleAt(mt.getSelectedIndex()),
                                (DefaultMutableTreeNode) mlp.tree.tree.getModel().getRoot());
                        // set select from tree
                        if (ss != null)
                            mlp.tree.tree.setSelectionPath(new TreePath(ss.getPath()));
                    }
                }
            }

            @Override
            public void mouseReleased(MouseEvent arg0) {
                // TODO Auto-generated method stub

            }

        });

        mlp.tree.tree.addKeyListener(new KeyListener() {

            @Override
            public void keyPressed(KeyEvent arg0) {
                // TODO Auto-generated method stub
                if (arg0.getKeyCode() == KeyEvent.VK_ENTER) {
                    // find path from name node

                    addTab(mlp.tree.tree.getLastSelectedPathComponent().toString());
                }
            }

            @Override
            public void keyReleased(KeyEvent arg0) {
                // TODO Auto-generated method stub

            }

            @Override
            public void keyTyped(KeyEvent arg0) {
                // TODO Auto-generated method stub

            }

        });

        setLayout(new java.awt.GridBagLayout());

        jSplitPane1.setRightComponent(jTabbedPane1);

        mlp.tree.tree.addTreeSelectionListener(new TreeSelectionListener() {

            @Override
            public void valueChanged(TreeSelectionEvent e) {
                // TODO Auto-generated method stub

            }

        });

        mlp.tree.tree.addMouseListener(new MouseListener() {

            @Override
            public void mouseClicked(MouseEvent arg0) {
                // TODO Auto-generated method stub
                if (arg0.getClickCount() == 1) {

                    Component aa = arg0.getComponent();
                    if (aa.getClass().getSimpleName().equals("JTree")) {
                        JTree tr = ((JTree) aa);
                        if (tr.getLastSelectedPathComponent() == null)
                            return;
                        addTab(tr.getLastSelectedPathComponent().toString());

                    }
                    ;
                }
            }

            @Override
            public void mouseEntered(MouseEvent arg0) {
                // TODO Auto-generated method stub

            }

            @Override
            public void mouseExited(MouseEvent arg0) {
                // TODO Auto-generated method stub

            }

            @Override
            public void mousePressed(MouseEvent arg0) {
                // TODO Auto-generated method stub

            }

            @Override
            public void mouseReleased(MouseEvent arg0) {
                // TODO Auto-generated method stub

            }

        });

        /*
         * mlp.jButton1.addActionListener(new ActionListener(){
         *
         * @Override public void actionPerformed(ActionEvent arg0) { // TODO
         * Auto-generated method stub
         *
         *
         * int s = jTabbedPane1.indexOfTab("tab1");
         *
         *
         *
         *
         * if (s==-1) { jTabbedPane1.addTabWithCloseButton("tab1", new
         * JPanel()); s= jTabbedPane1.indexOfTab("tab1");
         *
         *
         * } jTabbedPane1.setSelectedIndex(s); }
         *
         *
         * });
         */
        mlp.setMinimumSize(new Dimension(0, 0));
        jSplitPane1.setLeftComponent(mlp);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        add(jSplitPane1, gridBagConstraints);
        jSplitPane1.setDividerLocation(250);
    }// </editor-fold>
    // End of variables declaration

    // add tab from name
    public void addTab(String str) {

        if (str.equals(Lang.getInstance().translate("Send payment order")) || str.equals("IssueSendPaymentOrder")) {
            insertTab(Lang.getInstance().translate("Send Payment Order"), new IssueSendPaymentOrder());
            return;
        }

        if (str.equals(Lang.getInstance().translate("My Payments Orders"))
                || str.equals("MyOrderPaimentsSplitPanel")) {
            insertTab(Lang.getInstance().translate("My Payments Orders"), new MyOrderPaimentsSplitPanel());
            return;
        }

        if (str.equals(Lang.getInstance().translate("Favorite Persons")) || str.equals("PersonsFavoriteSplitPanel")) {
            insertTab(Lang.getInstance().translate("Favorite Persons"), new PersonsFavoriteSplitPanel());
            return;
        }

        if (str.equals(Lang.getInstance().translate("My Persons")) || str.equals("PersonsMySplitPanel")) {
            insertTab(Lang.getInstance().translate("My Persons"), new PersonsMySplitPanel());
            return;
        }
        if (str.equals(Lang.getInstance().translate("Search Persons")) || str.equals("SearchPersonsSplitPanel")) {
            insertTab(Lang.getInstance().translate("Search Persons"), new SearchPersonsSplitPanel());
            return;
        }
        if (str.equals(Lang.getInstance().translate("Issue Person")) || str.equals("IssuePersonPanel")) {
            insertTab(Lang.getInstance().translate("Issue Person"), new IssuePersonPanel());
            return;

        }

        if (str.equals(Lang.getInstance().translate("Insert Person")) || str.equals("InsertPersonPanel")) {
            insertTab(Lang.getInstance().translate("Insert Person"), new InsertPersonPanel());
            return;

        }

        if (str.equals(Lang.getInstance().translate("My Accounts")) || str.equals("MyAccountsSplitPanel")) {
            insertTab(Lang.getInstance().translate("My Accounts"), new MyAccountsSplitPanel());
            return;

        }

        if (str.equals(Lang.getInstance().translate("My Loans")) || str.equals("MyLoansSplitPanel")) {
            insertTab(Lang.getInstance().translate("My Loans"), new MyLoansSplitPanel());
            return;

        }

        if (str.equals(Lang.getInstance().translate("Favorite Accounts"))
                || str.equals("AccountsNameSearchSplitPanel")) {
            insertTab(Lang.getInstance().translate("Favorite Accounts"), new AccountsNameSearchSplitPanel());
            return;

        }

        if (str.equals(Lang.getInstance().translate("Favorite Documents"))
                || str.equals("FavoriteStatementsSplitPanel")) {
            insertTab(Lang.getInstance().translate("Favorite Documents"), new FavoriteStatementsSplitPanel());
            return;
        }
        if (str.equals(Lang.getInstance().translate("My Documents")) || str.equals("StatementsMySplitPanel")) {
            insertTab(Lang.getInstance().translate("My Documents"), new StatementsMySplitPanel());
            return;

        }
        if (str.equals(Lang.getInstance().translate("Search Documents"))
                || str.equals("SearchStatementsSplitPanel")) {
            insertTab(Lang.getInstance().translate("Search Documents"), new SearchStatementsSplitPanel());
            return;

        }
        if (str.equals(Lang.getInstance().translate("Issue Document")) || str.equals("IssueDocumentPanel")) {
            insertTab(Lang.getInstance().translate("Issue Document"), new IssueDocumentPanel());
            return;

        }
        if (str.equals(Lang.getInstance().translate("Incoming Mails")) || str.equals("IncomingMailsSplitPanel")) {
            insertTab(Lang.getInstance().translate("Incoming Mails"), new IncomingMailsSplitPanel());
            return;
        }
        if (str.equals(Lang.getInstance().translate("Outcoming Mails")) || str.equals("OutcomingMailsSplitPanel")) {
            insertTab(Lang.getInstance().translate("Outcoming Mails"), new OutcomingMailsSplitPanel());
            return;
        }
        if (str.equals(Lang.getInstance().translate("Send Mail")) || str.equals("MailSendPanel")) {
            insertTab(Lang.getInstance().translate("Send Mail"), new MailSendPanel(null, null, null));
            return;
        }

        if (str.equals(Lang.getInstance().translate("Favorite Assets")) || str.equals("AssetsFavoriteSplitPanel")) {
            insertTab(Lang.getInstance().translate("Favorite Assets"), new AssetsFavoriteSplitPanel());
            return;
        }

        if (str.equals(Lang.getInstance().translate("My Assets")) || str.equals("MyAssetsTab")) {
            insertTab(Lang.getInstance().translate("My Assets"), new MyAssetsTab());
            return;
        }
        if (str.equals(Lang.getInstance().translate("Search Assets")) || str.equals("SearchAssetsSplitPanel")) {
            insertTab(Lang.getInstance().translate("Search Assets"), new SearchAssetsSplitPanel(true));
            return;
        }
        if (str.equals(Lang.getInstance().translate("My Balance")) || str.equals("MyBalanceTab")) {
            insertTab(Lang.getInstance().translate("My Balance"), new MyBalanceTab());
            return;
        }
        if (str.equals(Lang.getInstance().translate("My Orders")) || str.equals("MyOrderTab")) {
            insertTab(Lang.getInstance().translate("My Orders"), new MyOrderTab());
            return;
        }
        if (str.equals(Lang.getInstance().translate("Issue Asset")) || str.equals("IssueAssetPanel")) {
            insertTab(Lang.getInstance().translate("Issue Asset"), new IssueAssetPanel());
            return;
        } else
        if (str.equals(Lang.getInstance().translate("Exchange")) || str.equals("ExchangePanel")) {
            insertTab(Lang.getInstance().translate("Exchange"), new ExchangePanel(null, null, null, null));
            return;
        } else
        if (str.equals(Lang.getInstance().translate("Withdraw Exchange")) || str.equals(WithdrawExchange.class.getSimpleName())) {
            insertTab(Lang.getInstance().translate("Withdraw Exchange"), new WithdrawExchange(null, null));
            return;
        }

        if (str.equals(Lang.getInstance().translate("Deposit Exchange")) || str.equals(DepositExchange.class.getSimpleName())) {
            insertTab(Lang.getInstance().translate("Deposit Exchange"), new DepositExchange(null, null));
            return;
        }

        if (str.equals(Lang.getInstance().translate("Search Templates")) || str.equals("SearchTemplatesSplitPanel")) {
            insertTab(Lang.getInstance().translate("Search Templates"), new SearchTemplatesSplitPanel());
            return;
        }
        if (str.equals(Lang.getInstance().translate("Favorite Templates"))
                || str.equals("TemplatesFavoriteSplitPanel")) {
            insertTab(Lang.getInstance().translate("Favorite Templates"), new TemplatesFavoriteSplitPanel());
            return;
        }
        if (str.equals(Lang.getInstance().translate("Issue Template")) || str.equals("IssueTemplatePanel")) {
            insertTab(Lang.getInstance().translate("Issue Template"), new IssueTemplatePanel());
            return;
        }
        if (str.equals(Lang.getInstance().translate("Create Status")) || str.equals("IssueStatusPanel")) {
            insertTab(Lang.getInstance().translate("Create Status"), new IssueStatusPanel());
            return;
        }
        if (str.equals(Lang.getInstance().translate("Favorite Statuses"))
                || str.equals("StatusesFavoriteSplitPanel")) {
            insertTab(Lang.getInstance().translate("Favorite Statuses"), new StatusesFavoriteSplitPanel());
            return;
        }
        if (str.equals(Lang.getInstance().translate("Search Statuses")) || str.equals("SearchStatusesSplitPanel")) {
            insertTab(Lang.getInstance().translate("Search Statuses"), new SearchStatusesSplitPanel());
            return;
        }
        if (BlockChain.DEVELOP_USE) {
            if (str.equals(Lang.getInstance().translate("My Unions")) || str.equals("MyUnionsTab")) {
                insertTab(Lang.getInstance().translate("My Unions"), new MyUnionsTab());
                return;
            }
            if (str.equals(Lang.getInstance().translate("Search Unions")) || str.equals("SearchUnionSplitPanel")) {
                insertTab(Lang.getInstance().translate("Search Unions"), new SearchUnionSplitPanel());
                return;
            }
            if (str.equals(Lang.getInstance().translate("Issue Union")) || str.equals("IssueUnionPanel")) {
                insertTab(Lang.getInstance().translate("Issue Union"), new IssueUnionPanel());
                return;
            }
        }


        if (str.equals(Lang.getInstance().translate("My Polls")) || str.equals("Polls_My_SplitPanel")) {
            insertTab(Lang.getInstance().translate("My Polls"), new Polls_My_SplitPanel());
            return;
        }
        if (str.equals(Lang.getInstance().translate("Search Polls")) || str.equals("SearchPollsSplitPanel")) {
            insertTab(Lang.getInstance().translate("Search Polls"), new SearchPollsSplitPanel());
            return;
        }
        if (str.equals(Lang.getInstance().translate("Issue Poll")) || str.equals("IssuePollPanel")) {
            insertTab(Lang.getInstance().translate("Issue Poll"), new IssuePollPanel());
            return;
        }
        if (str.equals(Lang.getInstance().translate("Favorite Polls")) || str.equals("PollsFavoriteSplitPanel")) {
            insertTab(Lang.getInstance().translate("Favorite Polls"), new PollsFavoriteSplitPanel());
            return;
        }


        if (str.equals(Lang.getInstance().translate("My Records")) || str.equals("MyTransactionsSplitPanel")) {
            insertTab(Lang.getInstance().translate("My Records"), MyTransactionsSplitPanel.getInstance());
            return;
        }
        if (str.equals(Lang.getInstance().translate("Favorite Records")) || str.equals("FavoriteTransactionsSplitPanel")) {
            insertTab(Lang.getInstance().translate("Favorite Records"), new FavoriteTransactionsSplitPanel());
            return;
        }
        if (str.equals(Lang.getInstance().translate("Search Records")) || str.equals("SearchTransactionsSplitPanel")) {
            insertTab(Lang.getInstance().translate("Search Records"), new SearchTransactionsSplitPanel());
            return;
        }
        if (str.equals(Lang.getInstance().translate("Unconfirmed Records"))
                || str.equals("UnconfirmedTransactionsPanel")) {
            insertTab(Lang.getInstance().translate("Unconfirmed Records"), new UnconfirmedTransactionsPanel());
            return;
        }
        if (str.equals(Lang.getInstance().translate("Other")) || str.equals("OtherSplitPanel")) {
            insertTab(Lang.getInstance().translate("Other"), new OtherSplitPanel());

            return;
        }

        if (str.equals(Lang.getInstance().translate("Console")) || str.equals("OtherConsolePanel")) {
            insertTab(Lang.getInstance().translate("Console"), new OtherConsolePanel());

            return;
        }

        if (str.equals(Lang.getInstance().translate("Blocks")) || str.equals("OtherSearchBlocks")) {
            insertTab(Lang.getInstance().translate("Blocks"), new OtherSearchBlocks());

            return;
        }

        if (str.equals(Lang.getInstance().translate("My Unique Hashes")) || str.equals("MyImprintsTab")) {
            insertTab(Lang.getInstance().translate("My Unique Hashes"), new MyImprintsTab());

            return;
        }

        if (str.equals(Lang.getInstance().translate("Search Unique Hashes"))
                || str.equals("ImprintsSearchSplitPanel")) {
            insertTab(Lang.getInstance().translate("Search Unique Hashes"), new ImprintsSearchSplitPanel());

            return;
        }

        if (str.equals(Lang.getInstance().translate("Favorite Unique Hashes"))
                || str.equals("ImprintsFavoriteSplitPanel")) {
            insertTab(Lang.getInstance().translate("Favorite Unique Hashes"), new ImprintsFavoriteSplitPanel());

            return;
        }

        if (str.equals(Lang.getInstance().translate("Issue Unique Hash")) || str.equals("IssueImprintPanel")) {
            insertTab(Lang.getInstance().translate("Issue Unique Hash"), new IssueImprintPanel());

            return;
        }

        if (str.equals(Lang.getInstance().translate("Issue Linked Hash")) || str.equals("IssueLinkedHashPanel")) {
            insertTab(Lang.getInstance().translate("Issue Linked Hash"), new IssueLinkedHashPanel());

            return;
        }

        if (str.equals(Lang.getInstance().translate("Search Linked Hash")) || str.equals("SearchLinkedHash")) {
            insertTab(Lang.getInstance().translate("Search Linked Hash"), new SearchLinkedHash());

            return;
        }

        if (BlockChain.DEVELOP_USE) {
            if (str.equals(Lang.getInstance().translate("Wallets Manager"))
                    || str.equals("WalletsManagerSplitPanel")) {
                insertTab(Lang.getInstance().translate("Wallets Manager"), new WalletsManagerSplitPanel());
                return;
            }
            
        }

        if (str.equals(Lang.getInstance().translate("Telegrams Panel"))
                || str.equals("TelegramSplitPanel")) {
            insertTab(Lang.getInstance().translate("Telegrams Panel"), new TelegramSplitPanel());

            return;
        }
        if (str.equals(Lang.getInstance().translate("All Telegrams Panel"))
                || str.equals("ALLTelegramPanel")) {
            insertTab(Lang.getInstance().translate("All Telegrams Panel"), new ALLTelegramPanel());

            return;
        }
    }

    // insert tab in tabbedpane
    public boolean insertTab(String str, JPanel pp) {
        int index = jTabbedPane1.indexOfTab(str);
        boolean inserted = false;
        if (index == -1) {
            jTabbedPane1.addTabWithCloseButton(str, pp);
            index = jTabbedPane1.indexOfTab(str);
            inserted = true;
        }
        jTabbedPane1.setSelectedIndex(index);

        return inserted;

    }

    // insert tab in tabbedpane
    public boolean insertTab(JPanel panel) {
        //String name = Lang.getInstance().translate(panel.getClass().getSimpleName());
        String name = Lang.getInstance().translate(panel.getName());
        int index = jTabbedPane1.indexOfTab(name);
        boolean inserted = false;
        if (index == -1) {
            jTabbedPane1.addTabWithCloseButton(name, panel);
            index = jTabbedPane1.indexOfTab(name);
            inserted = true;
        }
        jTabbedPane1.setSelectedIndex(index);

        return inserted;

    }

    // get node by name
    private DefaultMutableTreeNode getNodeByName(String sNodeName, DefaultMutableTreeNode parent) {
        if (parent != null)
            for (Enumeration e = parent.breadthFirstEnumeration(); e.hasMoreElements(); ) {
                DefaultMutableTreeNode current = (DefaultMutableTreeNode) e.nextElement();
                if (sNodeName.equals(current.getUserObject())) {
                    return current;
                }
            }
        return null;
    }

}
